# Install the python image
FROM python:3.12-slim-bookworm

# Install pipenv
RUN pip install pipenv

WORKDIR /app

# Install C compiler
RUN apt-get update && apt-get install -y \
    wget \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install the java 25 installous
RUN wget https://download.oracle.com/java/25/latest/jdk-25_linux-x64_bin.tar.gz && \
    tar -xzf jdk-25_linux-x64_bin.tar.gz -C /opt/ && \
    mv /opt/jdk-25* /opt/jdk-25 && \
    rm jdk-25_linux-x64_bin.tar.gz

ENV JAVA_HOME=/opt/jdk-25
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# Copy the source code into the container
COPY src/ /app/src/

# Install all the packages
WORKDIR /app/src/main/python
RUN pipenv install --system --deploy --skip-lock
RUN pip install -e .

# Copy the jar executable file
COPY a7-rl-testbed-0.0.1-SNAPSHOT.jar /app/simulation.jar

# Create volume points in the container
RUN mkdir -p /app/scenarios/sioux-falls/input/ /app/scenarios/sioux-falls/output/ \
             /app/shared_storage

ENV MATSIM_OUTPUT_BASE=/app/scenarios/sioux-falls/output/

VOLUME ["/app/scenarios/sioux-falls/input/", "/app/scenarios/sioux-falls/output/", "/app/shared_storage"]

WORKDIR /app

# End point
ENTRYPOINT ["python3"]
CMD ["/app/src/main/python/withinday/core/matsim.py"]
